baseURL = 'https://test.alexkasper.com/'
languageCode = 'en-us'
title = 'Alex Kasper'
[pagination]
  pagerSize = 15

[taxonomies]
tag = "tags"

[server]
  [[server.redirects]]
    from = "/**"
    to = "/404.html"
    status = 404
    
[[menus.main]]
name = "About"
pageRef = "/about"
weight = 10

[[menus.main]]
name = "News"
pageRef = "/news"
weight = 30

[[menus.main]]
name = "Events"
pageRef = "/events"
weight = 40

[[menus.main]]
name = "Files"
pageRef = "/files"
weight = 50

[[menus.main]]
name = "Contact"
pageRef = "/contact"
weight = 80


[permalinks]
  [permalinks.page]
    news = '/news/:contentbasename/:slug/'
    events = '/events/:contentbasename/:slug/'
    files = '/files/:contentbasename/:slug/'